### ISSUE TITLE
Evaluate code provided by Tulsa courtbot

### ISSUE THREAD

**Issue by ying1** [codeforsanjose/courtbot#2]
Tulsa: https://court.bot/
Tulsa github: https://github.com/codefortulsa/courtbot-python

- [ ] Determine an overview of how this courtbot works and what components.  General architecture
- [ ] Determine if there is a hook in which we can use to provided San Jose court data. 
- [ ] Reach out to understand what court data from Tulsa is stored.

**Comment by schmidtty** [comment]
### Courtbot San Jose ####
                           
![image](https://user-images.githubusercontent.com/6182306/129304770-687f4c35-c45d-49bf-91a3-e986189d5077.png)

Courtbot Tulse Code/Architecture Evaluation
...from the Courtbot Tulsa Playbook: 
# courtbot 2.0 #                                                                                                          

## Build Overview ##

### What’s powering it ###
- courtbot 2.0 is built with Python and 
- includes integrations with ...

          1. AWS Lambda
          2. Lex
          3. Heroku
          4. Twilio
          
### How does it work? ###
          - Text <-> Twilio <-> Lex Lambda <-> OSCN pypi <-> Return same path back
          - Note: OSCN utilities (OSCN pypi) is A python library for scraping case information from the 
            Oklahoma State Courts Network. For more information see [https://pydigger.com/pypi/oscn] 
![image](https://user-images.githubusercontent.com/6182306/129310653-3c10ab50-ec92-482c-8952-535043409996.png)


### Features ###
          Current state:
                    - Courtbot 2.0 only needs one phone number for everyone to use for 
                      SMS notifications: (844-329-6801)
                    - notifications can (also) be received via Facebook and Slack. 
          Future:
                    - bulk notification signup via the website.

### Implementation ###
          - you will need an API to plug into courtbot and access a python library that has 
            access to the data OSCN scraper: https://github.com/codefortulsa/oscn
                    - oscn > Python package source to provide an API for retrieving and parsing case records
                    -  the oscn scraper link has example code that
                         - queries a single case
                         - queries all cases for one county and one year
                         - queries multiple case types, multiple counties or, multiple years
                         - finds a string of text within a case list

### Conclusions ###
          1. the Tulsa solution uses a python library to retrieve the data, sort, find, etc
          2. every query results in a response to the user
          2. other implementations of similar SMS systems use 
             - Amazon Lex (the bot)
             - AWS Lambda (input validation)
             - Amazon DynamoDB (for storing data)        
          3. it might be just sufficient to only store 
             - case_identifier 
             - sms_source_number
             - notification_date
          4. likely main bot functions:
             - bot query based on SMS inputs
             - bot query based on notification_date (# of days before court date)
          5. using AWS seems ideal for non-profits
          6. Costs
             - one instance of courtbot, there are no costs to brigades
             - CfA has access to non-profit credits for Heroku, twilio, AWS
             - Code for Tulsa - has handled hosting costs in the past

**Comment by ying1** [comment]
Closing. Thanks for evaluation.
