### ISSUE TITLE
Notes from August 17, 2021 - courbot San Jose

### ISSUE THREAD

**Issue by schmidtty** [codeforsanjose/courtbot#6]
Notes from August 17, 2021 - Courtbot San Jose Update Since Last Meeting
 - Defined scope
 - Created tasks/issues
   - Access Santa Clara court data, API and determine if there are other considerations (done)
   - Evaluate code provided by Tulsa courtbot (done)
   - Evaluate approaches to develop Courtbot for San Jose (In the process)
   - Evaluate courtbot from Anchorage (In the process of completing)
   - Determine where we can host REST services and databases (pending)

**Comment by ying1** [comment]
I've added this to the minutes. 
https://docs.google.com/document/d/1wCdLNMhBR2dILi0lpyO6VEZgPnm9a_oS1ciDi583wyw/edit
